[package]
name = "aocr_cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
aocr = { path = "../aocr" }
clap = { workspace = true, features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
